from typing import Any


class DocumentBuilder:
    """Interface with a default implementation for builders."""

    def build_header(self, title: str = ""): ...

    def build_title(self, title: str): ...

    def build_content(self, content: str): ...

    def build_footer(self, copyright: str = ""): ...

    def get_result(self) -> Any: ...

    def reset(self): ...
